export const IPC = {
  workspaceGet: 'workspace:get',
  workspaceChoose: 'workspace:choose',
  workspaceUseRecent: 'workspace:use-recent',
  profilesSave: 'profiles:save',
  profilesRemove: 'profiles:remove',
  profilesSelect: 'profiles:select',
  sshConnect: 'ssh:connect',
  sshDisconnect: 'ssh:disconnect',
  sshStatus: 'ssh:status',
  sftpList: 'sftp:list',
  sftpHome: 'sftp:home',
  sftpMkdir: 'sftp:mkdir',
  sftpRename: 'sftp:rename',
  sftpRemove: 'sftp:remove',
  sftpUpload: 'sftp:upload',
  sftpDownload: 'sftp:download',
  sftpPrepareDrag: 'sftp:prepare-drag',
  sftpStartDrag: 'sftp:start-drag',
  transfersList: 'transfers:list',
  transfersCancel: 'transfers:cancel',
  transfersRetry: 'transfers:retry',
  transfersResolveConflict: 'transfers:resolve-conflict',
  dialogChooseDirectory: 'dialog:choose-directory',
  dialogChoosePrivateKey: 'dialog:choose-private-key',
  event: 'app:event'
} as const
